"""Shared UI constants for templates and artifacts.

This module contains shared values used by both:
- Web UI (templates/*.html via views.py)
- Email artifacts (artifacts.py)

Keeping these in one place prevents divergence.
"""
from datetime import datetime


# --- Colors ---

class Colors:
    """Shared color palette."""
    # Primary
    LINK = "#0066cc"
    LINK_HOVER = "#0052a3"

    # Text
    TEXT_PRIMARY = "#1a1a1a"
    TEXT_SECONDARY = "#666"
    TEXT_MUTED = "#888"
    TEXT_META = "#555"
    TEXT_BODY = "#333"

    # Borders
    BORDER = "#e0e0e0"
    BORDER_LIGHT = "#f0f0f0"

    # Summary box
    SUMMARY_BG = "#f8fafc"
    SUMMARY_BORDER = "#0066cc"

    # Refusal banner
    REFUSAL_BG = "#fef7e0"
    REFUSAL_BORDER = "#f9ab00"
    REFUSAL_TEXT = "#5f4b00"

    # Status
    STATUS_OK = "#2e7d32"


# --- Text Strings ---

class Strings:
    """Shared UI strings."""
    # Refusal messages (must match exactly for consistency)
    REFUSAL_MESSAGE = "Summary not generated — not enough source content"
    REFUSAL_COST_EXCEEDED = "Summary skipped — daily processing limit reached"

    # Labels
    SUMMARY_LABEL = "Summary"
    TOPICS_LABEL = "Topics:"
    SOURCES_LABEL_SINGULAR = "Sources: 1 article"
    SOURCES_LABEL_PLURAL = "Sources: {count} articles"

    # Headers
    DIGEST_TITLE = "News Digest — {day}"
    STORIES_COUNT_SINGULAR = "1 story from today's feeds"
    STORIES_COUNT_PLURAL = "{count} stories from today's feeds"

    # Run status
    LAST_UPDATED = "Last updated {time}"

    # Empty states
    NO_STORIES = "No stories found for this date."

    # Footer
    GENERATED_BY = "Generated by News Digest Engine"

    @classmethod
    def stories_count(cls, count: int) -> str:
        """Return appropriate stories count string."""
        if count == 1:
            return cls.STORIES_COUNT_SINGULAR
        return cls.STORIES_COUNT_PLURAL.format(count=count)

    @classmethod
    def sources_label(cls, count: int) -> str:
        """Return appropriate sources label."""
        if count == 1:
            return cls.SOURCES_LABEL_SINGULAR
        return cls.SOURCES_LABEL_PLURAL.format(count=count)


# --- Date Formatting ---

def format_date_short(iso_str: str) -> str:
    """Format ISO date string to 'Jan 14, 2026' format."""
    try:
        dt = datetime.fromisoformat(iso_str.replace("Z", "+00:00"))
        return dt.strftime("%b %d, %Y")
    except (ValueError, AttributeError):
        return iso_str[:10] if iso_str else ""


def format_datetime_friendly(iso_str: str) -> str:
    """Format ISO datetime to 'Jan 14, 2026 at 3:45 PM' format."""
    try:
        dt = datetime.fromisoformat(iso_str.replace("Z", "+00:00"))
        return dt.strftime("%b %d, %Y at %I:%M %p").replace(" 0", " ")
    except (ValueError, AttributeError):
        return ""
